spring.application.name=backendreplate

# H2 Database
spring.datasource.url=jdbc:h2:file:./data/replate-db
spring.datasource.driverClassName=org.h2.Driver

spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.defaults.restaurant-image-url=http://localhost:8080/images/DEFAULT_IMAGE_URL.png
app.defaults.volunteer-image-url=http://localhost:8080/images/DEFAULT_IMAGE_URL.png
app.defaults.ngo-image-url=http://localhost:8080/images/DEFAULT_IMAGE_URL.png

jwt.secret=replate-super-secret-key-2026-very-secure-32chars